announcement-format: '<gold><bold>%player%</bold> chose to join <white>%team%</white>!'
first-join-format: '<gold>Welcome %player%!</gold><newline>Use the buttons in front of you to choose your team!<newline><gray>Hint: Punch to use the buttons.'
spawn-protection-radius: 5
teams:
  1:
    name: 'Default'
    description: 'The default team is the best team of them all!'
    colour: '#ffffff'
    x: 0
    y: 69
    z: 0
    yaw: 0
    pitch: 0
    world: 'world'